// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        // 23-05-11 업데이트
        public const string achievement_collect_300_stars = "CgkIxJ3Xk4IYEAIQDg"; // <GPGSID> //
        public const string achievement_collect_1500_stars = "CgkIxJ3Xk4IYEAIQEw"; // <GPGSID> //
        public const string achievement_clear_700_level = "CgkIxJ3Xk4IYEAIQBg"; // <GPGSID> //
        public const string achievement_clear_500_level = "CgkIxJ3Xk4IYEAIQBQ"; // <GPGSID> //
        public const string achievement_clear_300_level = "CgkIxJ3Xk4IYEAIQBA"; // <GPGSID> //
        public const string achievement_collect_500_stars = "CgkIxJ3Xk4IYEAIQDw"; // <GPGSID> //
        public const string achievement_clear_10_level = "CgkIxJ3Xk4IYEAIQAQ"; // <GPGSID> //
        public const string achievement_clear_100_level = "CgkIxJ3Xk4IYEAIQAw"; // <GPGSID> //
        public const string achievement_collect_2000_stars = "CgkIxJ3Xk4IYEAIQFA"; // <GPGSID> //
        public const string achievement_collect_5000_stars = "CgkIxJ3Xk4IYEAIQFg"; // <GPGSID> //
        public const string achievement_collect_900_stars = "CgkIxJ3Xk4IYEAIQEQ"; // <GPGSID> //
        public const string achievement_collect_700_stars = "CgkIxJ3Xk4IYEAIQEA"; // <GPGSID> //
        public const string achievement_clear_2500_level = "CgkIxJ3Xk4IYEAIQCg"; // <GPGSID> //
        public const string achievement_collect_200_stars = "CgkIxJ3Xk4IYEAIQDQ"; // <GPGSID> //
        public const string achievement_clear_1500_level = "CgkIxJ3Xk4IYEAIQCA"; // <GPGSID> //
        public const string achievement_clear_50_level = "CgkIxJ3Xk4IYEAIQAg"; // <GPGSID> //
        public const string achievement_clear_2000_level = "CgkIxJ3Xk4IYEAIQCQ"; // <GPGSID> //
        public const string achievement_collect_1000_stars = "CgkIxJ3Xk4IYEAIQEg"; // <GPGSID> //
        public const string achievement_clear_1000_level = "CgkIxJ3Xk4IYEAIQBw"; // <GPGSID> //
        public const string achievement_collect_3000_stars = "CgkIxJ3Xk4IYEAIQFQ"; // <GPGSID> //
        public const string achievement_clear_3000_level = "CgkIxJ3Xk4IYEAIQCw"; // <GPGSID> //
        public const string achievement_collect_100_stars = "CgkIxJ3Xk4IYEAIQDA"; // <GPGSID> //

}

